### ISSUE TITLE
Error al timbrar factura

### ISSUE THREAD

**Issue by ivanporras** [itadmin01/Odoo_CFDI_3.2#5]
![Screenshot (43) (1)](https://user-images.githubusercontent.com/13451948/68514977-ff270380-0244-11ea-8a00-5da29d027fb8.png)

**Comment by garciagomez2** [comment]
Descargate la última versión del modulo, reemplaza los archivos, actualiza y reinicia el servicio, se hicieron cambios por el uso horario.

**Comment by ivanporras** [comment]
De hecho se resolvio, tenia mi servidor con otro horario.
